### PR TITLE
Quick Dependencies Update

### PR DESCRIPTION
**Pull request by rexthecoder**

### CODE REVIEW

**Review by bernardarhia — COMMENTED** [review]
We're not using these packages but somehow it has been added to package.json. Check it out and remove them "websocket",  "undici"

**Comment by rexthecoder** [comment]
> We're not using these packages but somehow it has been added to package.json. Check it out and remove them "websocket", "undici"

Yeah, the problem is that the mongodb-memory-server uses them internally but the version installed by nodemon has some issues. So this was the only solution that works 

cc @bernardarhia

**Comment by bernardarhia** [comment]
If mongoose-memory-server uses it, when you run npm update, it should update it internally... this is wrong... what command did you run for the update?
cc @rexthecoder

**Comment by rexthecoder** [comment]
> If mongoose-memory-server uses it, when you run npm update, it should update it internally... this is wrong... what command did you run for the update? cc @rexthecoder

Let me try if the nodemon files update without them

**Comment by rexthecoder** [comment]
@bernardarhia Deps has been removed.

**Review by bernardarhia — APPROVED** [review]

**Pull request merged**
